config/routes.rb
Rails.application.routes.draw do
  resources :datos_de_pasajes
  resources :tipo_de_servicios
  resources :servicios
  resources :pasajeros
  resources :itinerarios
  resources :paradas
  resources :ciudades
  resources :asiento_de_servicios
  resources :reservas
  resources :unidades

  match 'servicios_with_paradas_and_date' => 'servicios#servicios_with_paradas_and_date', :via => :post
  match 'servicio_asientos_disponibles' => 'servicios#asientos_disponibles', :via => :post
  
  root 'application#index'

end

app/models/pasajero.rb
class Pasajero < ActiveRecord::Base
	has_many :datos_de_pasajes 
end

app/controllers/pasajeros_controller.rb
class PasajerosController < ApplicationController
  before_action :set_pasajero, only: [:show, :edit, :update, :destroy]

  # GET /pasajeros
  # GET /pasajeros.json
  def index
    @pasajeros = Pasajero.all
  end

  # GET /pasajeros/1
  # GET /pasajeros/1.json
  def show
  end

  # GET /pasajeros/new
  def new
    @pasajero = Pasajero.new
  end

  # GET /pasajeros/1/edit
  def edit
  end

  # POST /pasajeros
  # POST /pasajeros.json
  def create
    @pasajero = Pasajero.new(pasajero_params)

    respond_to do |format|
      if @pasajero.save
        format.html { redirect_to @pasajero, notice: 'Pasajero was successfully created.' }
        format.json { render :show, status: :created, location: @pasajero }
      else
        format.html { render :new }
        format.json { render json: @pasajero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pasajeros/1
  # PATCH/PUT /pasajeros/1.json
  def update
    respond_to do |format|
      if @pasajero.update(pasajero_params)
        format.html { redirect_to @pasajero, notice: 'Pasajero was successfully updated.' }
        format.json { render :show, status: :ok, location: @pasajero }
      else
        format.html { render :edit }
        format.json { render json: @pasajero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pasajeros/1
  # DELETE /pasajeros/1.json
  def destroy
    @pasajero.destroy
    respond_to do |format|
      format.html { redirect_to pasajeros_url, notice: 'Pasajero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pasajero
      @pasajero = Pasajero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pasajero_params
      params.require(:pasajero).permit(:dni, :nombre)
    end
end

app/helpers/pasajeros_helper.rb
module PasajerosHelper
end

app/views/pasajeros/_form.html.slim
= form_for @pasajero do |f|
  - if @pasajero.errors.any?
    #error_explanation
      h2 = "#{pluralize(@pasajero.errors.count, "error")} prohibited this pasajero from being saved:"
      ul
        - @pasajero.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :dni
    = f.text_field :dni
  .field
    = f.label :nombre
    = f.text_field :nombre
  .actions = f.submit

app/views/pasajeros/edit.html.slim
h1 Editing pasajero

== render 'form'

= link_to 'Show', @pasajero
'|
= link_to 'Back', pasajeros_path

app/views/pasajeros/index.html.slim
h1 Listing pasajeros

table
  thead
    tr
      th Dni
      th Nombre
      th
      th
      th

  tbody
    - @pasajeros.each do |pasajero|
      tr
        td = pasajero.dni
        td = pasajero.nombre
        td = link_to 'Show', pasajero
        td = link_to 'Edit', edit_pasajero_path(pasajero)
        td = link_to 'Destroy', pasajero, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Pasajero', new_pasajero_path

app/views/pasajeros/new.html.slim
h1 New pasajero

== render 'form'

= link_to 'Back', pasajeros_path

app/views/pasajeros/show.html.slim
p#notice = notice

p
  strong Dni:
  = @pasajero.dni
p
  strong Nombre:
  = @pasajero.nombre

= link_to 'Edit', edit_pasajero_path(@pasajero)
/ '|
/ = link_to 'Back', pasajeros_path