config/routes.rb
Rails.application.routes.draw do
  resources :datos_de_pasajes
  resources :tipo_de_servicios
  resources :servicios
  resources :pasajeros
  resources :itinerarios
  resources :paradas
  resources :ciudades
  resources :asiento_de_servicios
  resources :reservas
  resources :unidades

  match 'servicios_with_paradas_and_date' => 'servicios#servicios_with_paradas_and_date', :via => :post
  match 'servicio_asientos_disponibles' => 'servicios#asientos_disponibles', :via => :post
  
  root 'application#index'

end

app/models/reserva.rb
class Reserva < ActiveRecord::Base
    has_one :datos_de_pasaje

    def dato_pasaje_numero
		if self.datos_de_pasaje_id == nil
			return 0
		else
			return self.datos_de_pasaje_id
		end
	end

end

app/controllers/reservas_controller.rb
class ReservasController < ApplicationController
  before_action :set_reserva, only: [:show, :edit, :update, :destroy]
  #include DatosDePasajesController

  # GET /reservas
  # GET /reservas.json
  def index
    @reservas = Reserva.all
  end

  # GET /reservas/1
  # GET /reservas/1.json
  def show

  end

  # GET /reservas/new
  def new
    @reserva = Reserva.new
    @datos_de_pasaje = DatosDePasaje.new
  end

  # GET /reservas/1/edit
  def edit
  end

  # POST /reservas
  # POST /reservas.json
  def create
    puts 'params[:datos_de_pasaje]', params[:datos_de_pasaje]
    puts 'params[:reserva]', params[:reserva]
    puts 'reserva_params', reserva_params

    p = params[:datos_de_pasaje][:pasajero_id]
    # s = params[:datos_de_pasaje][:servicio_id]
    asiento = params[:datos_de_pasaje][:asiento_de_servicio_id]

    @dp = DatosDePasaje.new(pasajero_id:p, asiento_de_servicio_id:asiento)
    @reserva = Reserva.new(reserva_params)
    @reserva.datos_de_pasaje = @dp
    @asiento = AsientoDeServicio.find(params[:datos_de_pasaje][:asiento_de_servicio_id])
    @dp.asiento_de_servicio = @asiento
    @asiento.estado = false

    # @reserva.save

    t = @reserva.transaction do
      @dp.save
      @reserva.save
      @asiento.save
    end

    respond_to do |format|
      if t
        format.html { redirect_to @reserva, notice: 'Reserva was successfully created.' }
        format.json { render :show, status: :created, location: @reserva }
      else
        format.html { render :new }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservas/1
  # PATCH/PUT /reservas/1.json
  def update
    respond_to do |format|
      if @reserva.update(reserva_params)
        format.html { redirect_to @reserva, notice: 'Reserva was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserva }
      else
        format.html { render :edit }
        format.json { render json: @reserva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservas/1
  # DELETE /reservas/1.json
  def destroy
    @reserva.destroy
    respond_to do |format|
      format.html { redirect_to reservas_url, notice: 'Reserva was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def cancelar_reserva
    @reserva = Reserva.find(params[:id])
    if @reserva.estado == 'Reservado'
      @datos_de_pasaje = DatosDePasaje.find(@reserva.datos_de_pasaje_id)
      @reserva = Reserva.update(@reserva.id, :estado => 'Cancelado')
      @asiento_de_servicio = AsientoDeServicio.update(@datos_de_pasaje.asiento_de_servicio_id, :estado => true)
      format.html { redirect_to @reserva, notice: 'Reserva fue cancelada' }
      format.json { render :show, status: :ok, location: @reserva }
    end
  end

  helper_method :cancelar_reserva

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserva
      @reserva = Reserva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserva_params
      params.require(:reserva).permit(:estado)
    end
end

app/helpers/reservas_helper.rb
module ReservasHelper
end

app/views/reservas/_form.html.slim
.field
  = label_tag :estado
  = hidden_field_tag :estado, 'Reservado'
  / = input_tag :estado, :as => :hidden, :input_html => { :value => "Reservado" }
  / = hidden_field(:reserva, :estado)
  / = f.select(:estado, options_for_select([['Reservado'],['Cancelado']]))

app/views/reservas/edit.html.slim
h1 Editing reserva

== render 'form'

= link_to 'Show', @reserva
'|
= link_to 'Back', reservas_path

app/views/reservas/index.html.slim
h1 Listing reservas


table
  thead
    tr
      th Estado
      th
      th
      th

  tbody
    - @reservas.each do |reserva|
      tr
        td = reserva.estado
        td = link_to 'Show', reserva
        td = link_to 'Edit', edit_reserva_path(reserva)
        td = link_to 'Destroy', reserva, data: {:confirm => 'Are you sure?'}, :method => :delete
        if reserva.estado == 'Reservado'
          td = button_to 'Cancelar', reserva, data: {:confirm => 'Está seguro que quiere Cancelar la Reserva?'}, :method => ReservasController.new.cancelar_reserva
br

= link_to 'New Reserva', new_reserva_path

app/views/reservas/new.html.slim
div.row
  div#header align="center"
    h1 Registrar Datos - Reservar Pasaje

div.row
  = form_for @reserva do |f|
    - if @reserva.errors.any?
      #error_explanation
        h2 = "#{pluralize(@reserva.errors.count, "error")} prohibited this reserva from being saved:"
        ul
          - @reserva.errors.full_messages.each do |message|
            li = message

    .field
      / = label_tag :estado
      = hidden_field_tag "reserva[estado]", 'Reservado'

    / .actions = f.submit
    == render 'datos_de_pasajes/partial_form.html'


    / = link_to 'Back', reservas_path

app/views/reservas/show.html.slim
p#notice = notice

p
  strong Reserva Nro:
  = @reserva.id

p
  strong Estado:
  = @reserva.estado

p
  strong Nombre del Pasajero:
  = @reserva.datos_de_pasaje.pasajero.nombre

p
  strong DNI del Pasajero:
  = @reserva.datos_de_pasaje.pasajero.dni

p
  strong Número de Asiento:
  = @reserva.datos_de_pasaje.asiento_de_servicio.nro

= link_to 'Edit', edit_reserva_path(@reserva)
/ '|
/ = link_to 'Back', reservas_path