config/routes.rb
Rails.application.routes.draw do
  resources :datos_de_pasajes
  resources :tipo_de_servicios
  resources :servicios
  resources :pasajeros
  resources :itinerarios
  resources :paradas
  resources :ciudades
  resources :asiento_de_servicios
  resources :reservas
  resources :unidades

  match 'servicios_with_paradas_and_date' => 'servicios#servicios_with_paradas_and_date', :via => :post
  match 'servicio_asientos_disponibles' => 'servicios#asientos_disponibles', :via => :post
  
  root 'application#index'

end

app/models/datos_de_pasaje.rb
class DatosDePasaje < ActiveRecord::Base
	belongs_to :asiento_de_servicio
	belongs_to :pasajero
	belongs_to :servicio
	# belongs_to :pasaje

	def numero
		if self.id == nil
			dato = DatosDePasaje.last.id
			return dato +1
		else
			return self.id
		end
	end

	def reserva_numero
		if self.reserva_id == nil
			return 0
		else
			return self.reserva_id
		end
	end
	# def venta_numero
	# 	if self.id == nil
	# 		return 0
	# 	else
	# 		return self.id
	# 	end
	# end
end

app/controllers/datos_de_pasajes_controller.rb
class DatosDePasajesController < ApplicationController
  before_action :set_datos_de_pasaje, only: [:show, :edit, :update, :destroy]

  # GET /datos_de_pasajes
  # GET /datos_de_pasajes.json
  def index
    @datos_de_pasajes = DatosDePasaje.all
  end

  # GET /datos_de_pasajes/1
  # GET /datos_de_pasajes/1.json
  def show
  end

  # GET /datos_de_pasajes/new
  def new
    @datos_de_pasaje = DatosDePasaje.new
  end

  # GET /datos_de_pasajes/1/edit
  def edit
  end

  # POST /datos_de_pasajes
  # POST /datos_de_pasajes.json
  def create
    @datos_de_pasaje = DatosDePasaje.new(datos_de_pasaje_params)

    respond_to do |format|
      if @datos_de_pasaje.save
        format.html { redirect_to @datos_de_pasaje, notice: 'Datos de pasaje was successfully created.' }
        format.json { render :show, status: :created, location: @datos_de_pasaje }
      else
        format.html { render :new }
        format.json { render json: @datos_de_pasaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos_de_pasajes/1
  # PATCH/PUT /datos_de_pasajes/1.json
  def update
    respond_to do |format|
      if @datos_de_pasaje.update(datos_de_pasaje_params)
        format.html { redirect_to @datos_de_pasaje, notice: 'Datos de pasaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @datos_de_pasaje }
      else
        format.html { render :edit }
        format.json { render json: @datos_de_pasaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_de_pasajes/1
  # DELETE /datos_de_pasajes/1.json
  def destroy
    @datos_de_pasaje.destroy
    respond_to do |format|
      format.html { redirect_to datos_de_pasajes_url, notice: 'Datos de pasaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #private
    # Use callbacks to share common setup or constraints between actions.
    def set_datos_de_pasaje
      @datos_de_pasaje = DatosDePasaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datos_de_pasaje_params
      #params.require[:datos_de_pasaje]
      params.require(:datos_de_pasaje).permit(:asiento_de_servicio_id, :pasajero_id, :servicio_id)
    end
end

app/helpers/datos_de_pasajes_helper.rb
module DatosDePasajesHelper
end

app/views/datos_de_pasajes/_form.html.slim
= form_for @datos_de_pasaje do |f|
  - if @datos_de_pasaje.errors.any?
    #error_explanation
      h2 = "#{pluralize(@datos_de_pasaje.errors.count, "error")} prohibited this datos_de_pasaje from being saved:"
      ul
        - @datos_de_pasaje.errors.full_messages.each do |message|
          li = message
  field 
    = f.label 'Nombre del Pasajero: '
    = f.collection_select :pasajero_id, Pasajero.all, :id, :nombre
  field 
    = f.label 'Número de Asiento: '
    = f.collection_select :asiento_de_servicio_id, AsientoDeServicio.where(estado: true), :id, :nro
  / .field
  /     = f.label @datos_de_pasaje.numero
  .actions = f.submit

app/views/datos_de_pasajes/_partial_form.html.slim
= form_for @datos_de_pasaje do |f|
  - if @datos_de_pasaje.errors.any?
    #error_explanation
      h2 = "#{pluralize(@datos_de_pasaje.errors.count, "error")} prohibited this datos_de_pasaje from being saved:"
      ul
        - @datos_de_pasaje.errors.full_messages.each do |message|
          li = message

  div#pasajero.row
    div.col-md-12
      p.field 
        = f.label 'Pasajero: '
        = f.collection_select :pasajero_id, Pasajero.all, :id, :nombre
  
  hr
  
  div.row
    div#paradas_date.col-md-5
      p.field
        = f.label 'Parada Origen: '
        = select_tag "parada_origen", options_from_collection_for_select(Parada.all, "id", "nombre")

      p.field
        = f.label 'Parada Destino: '
        = select_tag "parada_destino", options_from_collection_for_select(Parada.all, "id", "nombre")  

      p.field
        = f.label "Fecha: "
        = select_date Date.today, :id => "datos_de_pasaje[fecha]", class: "col-md-offset-12"
      
      p.field.col-md-offset-4
        input#servicio name="datos_de_pasaje[servicio_id]" type="hidden"
        / = hidden_field_tag "servicio_id"
        span#btnServicio.btn.btn-info.btn-lg Buscar Servicio

    div.col-md-7
      p.field
        table.table
          thead
            tr
              th #
              th Fecha
              th Hora de Salida
              th Hora de Llegada
              th Itinerario

          tbody#servicios
            td
            td Seleccione Origen y Destino

      p#asientos.field

      p.field
        span#btnReservarPasaje.btn.btn-success.btn-lg Reservar Pasaje

app/views/datos_de_pasajes/edit.html.slim
h1 Editing datos_de_pasaje

== render 'form'

= link_to 'Show', @datos_de_pasaje
'|
= link_to 'Back', datos_de_pasajes_path

app/views/datos_de_pasajes/index.html.slim
h1 Listing datos_de_pasajes

table
  thead
    tr
      th
      th
      th

  tbody
    - @datos_de_pasajes.each do |datos_de_pasaje|
      tr
        td = link_to 'Show', datos_de_pasaje
        td = link_to 'Edit', edit_datos_de_pasaje_path(datos_de_pasaje)
        td = link_to 'Destroy', datos_de_pasaje, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Datos de pasaje', new_datos_de_pasaje_path

app/views/datos_de_pasajes/new.html.slim
h1 New datos_de_pasaje

== render 'form'

= link_to 'Back', datos_de_pasajes_path

app/views/datos_de_pasajes/show.html.slim
p#notice = notice

p vamos a suponer que soy un pasajero

p y un origen

p y un destino

p y otra fruta rara

p
  strong Numero: 
  = @datos_de_pasaje.numero

p
  strong Numero de reserva: 
  = @datos_de_pasaje.reserva_numero

/= render :partial => '/reservas/form', :log_entry => @datos_de_pasaje.Reservas.new

= link_to 'Edit', edit_datos_de_pasaje_path(@datos_de_pasaje)
/ '|
/ = link_to 'Back', datos_de_pasajes_path