config/routes.rb
Rails.application.routes.draw do
  resources :datos_de_pasajes
  resources :tipo_de_servicios
  resources :servicios
  resources :pasajeros
  resources :itinerarios
  resources :paradas
  resources :ciudades
  resources :asiento_de_servicios
  resources :reservas
  resources :unidades

  match 'servicios_with_paradas_and_date' => 'servicios#servicios_with_paradas_and_date', :via => :post
  match 'servicio_asientos_disponibles' => 'servicios#asientos_disponibles', :via => :post
  
  root 'application#index'

end

app/models/tipo_de_servicio.rb
class TipoDeServicio < ActiveRecord::Base
end

app/controllers/tipo_de_servicios_controller.rb
class TipoDeServiciosController < ApplicationController
  before_action :set_tipo_de_servicio, only: [:show, :edit, :update, :destroy]

  # GET /tipo_de_servicios
  # GET /tipo_de_servicios.json
  def index
    @tipo_de_servicios = TipoDeServicio.all
  end

  # GET /tipo_de_servicios/1
  # GET /tipo_de_servicios/1.json
  def show
  end

  # GET /tipo_de_servicios/new
  def new
    @tipo_de_servicio = TipoDeServicio.new
  end

  # GET /tipo_de_servicios/1/edit
  def edit
  end

  # POST /tipo_de_servicios
  # POST /tipo_de_servicios.json
  def create
    @tipo_de_servicio = TipoDeServicio.new(tipo_de_servicio_params)

    respond_to do |format|
      if @tipo_de_servicio.save
        format.html { redirect_to @tipo_de_servicio, notice: 'Tipo de servicio was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_de_servicio }
      else
        format.html { render :new }
        format.json { render json: @tipo_de_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_de_servicios/1
  # PATCH/PUT /tipo_de_servicios/1.json
  def update
    respond_to do |format|
      if @tipo_de_servicio.update(tipo_de_servicio_params)
        format.html { redirect_to @tipo_de_servicio, notice: 'Tipo de servicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_de_servicio }
      else
        format.html { render :edit }
        format.json { render json: @tipo_de_servicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_de_servicios/1
  # DELETE /tipo_de_servicios/1.json
  def destroy
    @tipo_de_servicio.destroy
    respond_to do |format|
      format.html { redirect_to tipo_de_servicios_url, notice: 'Tipo de servicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_de_servicio
      @tipo_de_servicio = TipoDeServicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_de_servicio_params
      params.require(:tipo_de_servicio).permit(:nombre)
    end
end

app/helpers/tipo_de_servicios_helper.rb
module TipoDeServiciosHelper
end

app/views/tipo_de_servicios/_form.html.slim
= form_for @tipo_de_servicio do |f|
  - if @tipo_de_servicio.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tipo_de_servicio.errors.count, "error")} prohibited this tipo_de_servicio from being saved:"
      ul
        - @tipo_de_servicio.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :nombre
    = f.text_field :nombre
  .actions = f.submit

app/views/tipo_de_servicios/edit.html.slim
h1 Editing tipo_de_servicio

== render 'form'

= link_to 'Show', @tipo_de_servicio
'|
= link_to 'Back', tipo_de_servicios_path

app/views/tipo_de_servicios/index.html.slim
h1 Listing tipo_de_servicios

table
  thead
    tr
      th Nombre
      th
      th
      th

  tbody
    - @tipo_de_servicios.each do |tipo_de_servicio|
      tr
        td = tipo_de_servicio.nombre
        td = link_to 'Show', tipo_de_servicio
        td = link_to 'Edit', edit_tipo_de_servicio_path(tipo_de_servicio)
        td = link_to 'Destroy', tipo_de_servicio, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tipo de servicio', new_tipo_de_servicio_path

app/views/tipo_de_servicios/new.html.slim
h1 New tipo_de_servicio

== render 'form'

= link_to 'Back', tipo_de_servicios_path

app/views/tipo_de_servicios/show.html.slim
p#notice = notice

p
  strong Nombre:
  = @tipo_de_servicio.nombre

= link_to 'Edit', edit_tipo_de_servicio_path(@tipo_de_servicio)
/ '|
/ = link_to 'Back', tipo_de_servicios_path